### ISSUE TITLE
iPhone-sized but expecting iPad-size?

### ISSUE THREAD

**Issue by aaronhmiller** [landonf/simlaunch#1]
great little app, thanks! i've an issue with a demo showing up at iPhone sizes though when i run it in the "real" simulator it runs at full iPad-app size. Any ideas of how to fix? I'm using the 1.0b3 binary distribution.

**Comment by massimobio** [comment]
I have the same issue. The re-bundled app opens up the iPad correctly but then displays in iPhone simulation mode within the iPad.

**Comment by postmechanical** [comment]
Same problem here.

**Comment by victor** [comment]
Looks like the problem is in the way the property list key for the supported device families of the SDKs changed from the 3.x to the 4.x versions

In version 3.x, the key was `UIDeviceFamily`.
In version 4.x, the key (or rather, keypath) is `DefaultProperties.SUPPORTED_DEVICE_FAMILIES`

Since the code is not demanding this key as a required one when inspecting the SDK, there's no error logged, and an iPhone device family assumed by default

**Comment by landonf** [comment]
Should now be resolved.
